--CAU 1--
CREATE DATABASE QuanLyBanHang

CREATE TABLE KHACHHANG (
	MAKH CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY,
);

CREATE TABLE NHANVIEN (
	MANV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
);

CREATE TABLE SANPHAM (
	MASP CHAR(4) PRIMARY KEY,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY
);

CREATE TABLE HOADON (
	SOHD INT PRIMARY KEY, 
	NGHD SMALLDATETIME,
	MAKH CHAR(4),
	MANV CHAR(4),
	TRIGIA MONEY,
);

CREATE TABLE CTHD (
	SOHD INT, 
	MASP CHAR(4),
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MASP)
);

ALTER TABLE HOADON ADD
CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTHD ADD
CONSTRAINT FK_CTHD_HD FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD),
CONSTRAINT FK_CTHD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

--CAU 2--
ALTER TABLE SANPHAM ADD GHICHU VARCHAR(20)

--CAU 3--
ALTER TABLE KHACHHANG ADD LOAIKH TINYINT

--CAU 4--
ALTER TABLE SANPHAM ALTER COLUMN GHICHU VARCHAR(100)

--CAU 5--
ALTER TABLE SANPHAM DROP COLUMN GHICHU

--CAU 6--
ALTER TABLE KHACHHANG ALTER COLUMN LOAIKH VARCHAR(30)

--CAU 7--
ALTER TABLE SANPHAM ADD CONSTRAINT CHK_DVT
CHECK((DVT='cay') OR (DVT='hop') OR (DVT='cai') OR (DVT='quyen') OR (DVT='chuc'))

--CAU 8--
ALTER TABLE SANPHAM ADD CHECK(GIA > 500)

--CAU 9--
ALTER TABLE HOADON ADD CONSTRAINT CHK_SL 
CHECK (TRIGIA!=0)

--CAU 10--
ALTER TABLE KHACHHANG ADD CHECK (NGDK > NGSINH)
