-- BAI TAP 2 PHAN II CAU 17 QUANLYGIAOVU
CREATE TRIGGER tg_check_slsv ON LOP 
AFTER INSERT, UPDATE
AS 
BEGIN 
	DECLARE @SiSo TINYINT, @MaLop CHAR(3), @SLHV TINYINT

	SELECT @SiSo = SISO, @MaLop = MALOP FROM INSERTED
	SELECT @SLHV = (SELECT COUNT(MAHV)
					FROM HOCVIEN
					WHERE MALOP = @MaLop
					GROUP BY MALOP)
	IF(@SiSo = @SLHV) 
	BEGIN
		PRINT('Them moi lop thanh cong')
	END
	ELSE 
	BEGIN 
		PRINT('Si so cua lop phai bang so luong hoc vien');
		ROLLBACK TRANSACTION;
	END
END