-- BAI TAP 2 PHAN II CAU 16 QUANLYGIAOVU
CREATE TRIGGER tg_check_giangday_mhtoida
ON GIANGDAY 
AFTER INSERT, UPDATE
AS 
BEGIN 
	DECLARE @SOMONHOC INT
	DECLARE @MALOP CHAR(3)
	DECLARE @HOCKY TINYINT 
	DECLARE @NAM SMALLINT
	SELECT @MALOP = MALOP, @HOCKY = HOCKY, @NAM = NAM FROM INSERTED

	SELECT @SOMONHOC = (SELECT COUNT(MAMH) FROM GIANGDAY
						WHERE MALOP = @MALOP AND HOCKY =  @HOCKY AND NAM = @NAM
						GROUP BY MALOP )
	IF(@SOMONHOC < 3)
		PRINT('Them moi giang day thanh cong')
	ELSE 
		BEGIN 
			RAISERROR('Moi hoc ky mot nam, mot lop chi duoc hoc toi da 3 mon', 16, 1);
			ROLLBACK TRANSACTION;
		END
END