-- BAI TAP 2 - PHAN I CAU 9 QUANLYGIAOVU
CREATE TRIGGER trg_lptr_hsi ON LOP
FOR INSERT
AS
BEGIN
	DECLARE @LopTrg char(5), @MaLop char(3)
	SELECT @LopTrg = TRGLOP, @MaLop = MALOP
	FROM INSERTED
	
	IF (@MaLop <> (SELECT MALOP FROM HOCVIEN WHERE MAHV = @LopTrg))
	BEGIN
		PRINT 'LOI: LOP KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN 
		PRINT 'THEM MOI MOT LOP THANH CONG'
	END
END