-- BAI TAP 2 PHAN I CAU 22 QUANLYGIAOVU
CREATE TRIGGER tg_check_hocxong
ON KETQUATHI
AFTER INSERT, UPDATE
AS 
BEGIN 
	DECLARE @NGTHI SMALLDATETIME
	DECLARE @MAMH VARCHAR(10)
	DECLARE @DENNGAY SMALLDATETIME 
	DECLARE @MAHV CHAR(5)
	DECLARE @MALOP CHAR(3)


	SELECT @NGTHI = NGTHI, @MAMH = MAMH, @MAHV = MAHV FROM INSERTED
	SELECT @MALOP = MALOP FROM HOCVIEN 
	WHERE MAHV = @MAHV 
	SELECT @DENNGAY = DENNGAY FROM GIANGDAY 
	WHERE MAMH = @MAMH AND MALOP = @MALOP 

	IF(@NGTHI > @DENNGAY)
		PRINT('Them moi ket qua thi thanh cong')
	ELSE 
		BEGIN 
			RAISERROR('Ngay thi phai lon hon ngay ket thuc mon hoc', 16, 1);
			ROLLBACK TRANSACTION;
		END
END