-- BAI TAP 2 PHAN I CAU 10 QUANLYGIAOVU
CREATE TRIGGER trg_tgk_hvi ON KHOA
FOR INSERT
AS
BEGIN 
	DECLARE @TrgKhoa char(4), @MaKhoa varchar(4)
	SELECT @TrgKhoa = TRGKHOA
	FROM INSERTED

	IF (@MaKhoa = (SELECT MAKHOA FROM GIAOVIEN WHERE MAGV = @TrgKhoa)
		AND ((SELECT HOCVI FROM GIAOVIEN WHERE MAGV = @TrgKhoa) IN ('TS', 'PTS')))
	BEGIN 
		PRINT 'LOI: TRUONG KHOA KHONG HOP LE'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI MOT KHOA THANH CONG'
	END
END