-- BAI TAP 2 PHAN I CAU 19 QUANLYGIAOVU
CREATE TRIGGER tg_check_mucluong
ON GIAOVIEN 
AFTER INSERT, UPDATE 
AS 
BEGIN 
	DECLARE @HOCVI VARCHAR(10)
	DECLARE @HOCHAM VARCHAR(10)
	DECLARE @MUCLUONG MONEY 

	DECLARE @HOCVI1 VARCHAR(10)
	DECLARE @HOCHAM1 VARCHAR(10)
	DECLARE @MUCLUONG1 MONEY

	SELECT @HOCVI = HOCVI, @HOCHAM = HOCHAM, @MUCLUONG = MUCLUONG FROM INSERTED

	SELECT TOP 1 @MUCLUONG1 = MUCLUONG FROM GIAOVIEN 
	WHERE HOCVI = @HOCVI AND HOCHAM = @HOCHAM

	IF(@MUCLUONG = @MUCLUONG1) 
			PRINT('Them moi giao vien thanh cong')
	ELSE 
		BEGIN 
			RAISERROR('Giao vien cung hoc vi, hoc ham nhung muc luong khac nhau', 16, 1);
			ROLLBACK TRANSACTION;
		END
END
