-- BAI TAP 2 PHAN I CAU 24 QUANLYGIAOVU
CREATE TRIGGER tg_check_ngthi ON KETQUATHI
AFTER INSERT, UPDATE
AS 
BEGIN 
	DECLARE @NGTHI SMALLDATETIME, @MAMH VARCHAR(10), @DENNGAY SMALLDATETIME, @MAHV CHAR(5), @MALOP CHAR(3)

	SELECT @NGTHI = NGTHI, @MAMH = MAMH, @MAHV = MAHV FROM INSERTED
	SELECT @MALOP = MALOP FROM HOCVIEN 
	WHERE MAHV = @MAHV 
	SELECT @DENNGAY = DENNGAY FROM GIANGDAY 
	WHERE MAMH = @MAMH AND MALOP = @MALOP 

	IF(@NGTHI > @DENNGAY)
		PRINT('Them moi ket qua thi thanh cong')
	ELSE 
		BEGIN 
			PRINT('Ngay thi phai lon hon ngay ket thuc mon hoc');
			ROLLBACK TRANSACTION;
		END
END