-- BAI TAP 2 PHAN I CAU 21 QUANLYGIAOVU
CREATE TRIGGER tg_check_ngthilai
ON KETQUATHI
AFTER INSERT, UPDATE 
AS 
BEGIN 
	DECLARE @MAHV CHAR(5)
	DECLARE @MAMH VARCHAR(10)
	DECLARE @NGTHI SMALLDATETIME

	DECLARE @NGTHI1 SMALLDATETIME

	SELECT @MAHV = MAHV, @MAMH = MAMH, @NGTHI = NGTHI FROM INSERTED
	SELECT @NGTHI1 = NGTHI FROM KETQUATHI 
	WHERE @MAHV = MAHV AND @MAMH = MAMH 

	IF(@NGTHI > @NGTHI1)
		PRINT('Them moi ket qua thi thanh cong')
	ELSE 
		BEGIN
			RAISERROR('Hoc vien thi lai nhung ngay thi nho hon ngay thi truoc do', 16, 1);
			ROLLBACK TRANSACTION ;
		END
END