-- BAI TAP 2 PHAN I CAU 24 QUANLYGIAOVU
CREATE TRIGGER tg_check_phancong
ON GIANGDAY 
AFTER INSERT, UPDATE 
AS 
BEGIN 
	DECLARE @MAMH VARCHAR(10)
	DECLARE @MAGV CHAR(4)

	DECLARE @MAKHOA VARCHAR(4)
	DECLARE @MAKHOA1 VARCHAR(4)

	SELECT @MAMH = MAMH, @MAGV = MAGV FROM INSERTED 
	SELECT @MAKHOA = MAKHOA FROM MONHOC 
	WHERE MAMH = @MAMH 

	SELECT @MAKHOA1 = MAKHOA FROM GIAOVIEN 
	WHERE MAGV = @MAGV 

	IF(@MAKHOA = @MAKHOA1)
		PRINT('Them moi giang day thanh cong')
	ELSE 
		BEGIN 
			RAISERROR('Giang vien duoc phan cong khac khoa phu trach', 16, 1);
			ROLLBACK TRANSACTION;
		END
END