USE QuanLyBanHang

-- BAI TAP 1
-- PHAN III CAU 12 VA CAU 13
-- CAU 12
SELECT SOHD
FROM CTHD
WHERE MASP IN ('BB01', 'BB02') AND SL BETWEEN 10 AND 20

-- CAU 13
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB01' AND SL BETWEEN 10 AND 20
INTERSECT
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB02' AND SL BETWEEN 10 AND 20

-- BAI TAP 4
-- PHAN III CAU 14 DEN 18
-- CAU 14
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
UNION
SELECT DISTINCT CTHD.MASP, TENSP
FROM CTHD JOIN HOADON
ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM
ON CTHD.MASP = SANPHAM.MASP
WHERE NGHD = '2007-01-01'

-- CAU 15
SELECT MASP, TENSP
FROM SANPHAM
EXCEPT
SELECT DISTINCT CTHD.MASP, TENSP
FROM CTHD JOIN HOADON
ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM
ON CTHD.MASP = SANPHAM.MASP

-- CAU 16
SELECT MASP, TENSP
FROM SANPHAM
EXCEPT
SELECT DISTINCT CTHD.MASP, TENSP
FROM CTHD JOIN HOADON
ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM
ON CTHD.MASP = SANPHAM.MASP
WHERE YEAR(NGHD) = 2006

-- CAU 17
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc'
EXCEPT
SELECT DISTINCT CTHD.MASP, TENSP
FROM CTHD JOIN HOADON
ON CTHD.SOHD = HOADON.SOHD
JOIN SANPHAM
ON CTHD.MASP = SANPHAM.MASP
WHERE YEAR(NGHD) = 2006 AND NUOCSX = 'Trung Quoc'

-- CAU 18
SELECT DISTINCT SOHD
FROM CTHD C1
WHERE NOT EXISTS (
	SELECT MASP
	FROM SANPHAM
	WHERE NUOCSX = 'Singapore'
	EXCEPT
	SELECT MASP
	FROM CTHD C2
	WHERE C1.SOHD = C2.SOHD
)


