USE QuanLyGiaoVu

-- BAI TAP 2
-- PHAN II CAU 1 DEN CAU 4
-- CAU 1
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (
	SELECT TRGKHOA AS A
	FROM GIAOVIEN JOIN KHOA
	ON GIAOVIEN.MAGV = KHOA.TRGKHOA
)

-- CAU 2
UPDATE HOCVIEN
SET DIEMTB = DTB_HOCVIEN.DTB
FROM HOCVIEN LEFT JOIN (	
	SELECT KETQUATHI.MAHV, AVG(KETQUATHI.DIEM) AS DTB 
	FROM KETQUATHI INNER JOIN (
		SELECT MAHV, MAMH, MAX(LANTHI) LANTHIMAX
		FROM KETQUATHI
		GROUP BY MAHV, MAMH
	) B 
	ON KETQUATHI.MAHV = B.MAHV AND KETQUATHI.MAMH = B.MAMH AND KETQUATHI.LANTHI = B.LANTHIMAX 
	GROUP BY KETQUATHI.MAHV
) DTB_HOCVIEN
ON HOCVIEN.MAHV = DTB_HOCVIEN.MAHV

SELECT *
FROM HOCVIEN
-- CAU 3
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN (
	SELECT MAHV
	FROM KETQUATHI
	WHERE LANTHI = 3 AND DIEM < 5
)

-- CAU 4
UPDATE HOCVIEN
SET XEPLOAI = CASE
		WHEN DIEMTB >= 9 THEN 'XS'
		WHEN DIEMTB >= 8 THEN 'G'
		WHEN DIEMTB >= 6.5 THEN 'K'
		WHEN DIEMTB >= 5 THEN 'TB'
		ELSE 'Y'
END;

-- BAI TAP 3
-- PHAN III CAU 6 DEN CAU 10
-- CAU 6
SELECT TENMH
FROM MONHOC
WHERE MAMH IN (
	SELECT MAMH
	FROM GIANGDAY 
	WHERE MAGV IN (
		SELECT MAGV
		FROM GIAOVIEN
		WHERE HOTEN = 'Tran Tam Thanh'
	)
	AND HOCKY = 1 AND NAM = 2006
)

-- CAU 7
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN (
	SELECT MAMH
	FROM GIANGDAY
	WHERE MAGV IN (
		SELECT MAGVCN
		FROM LOP
		WHERE MALOP = 'K11'
	) AND HOCKY = 1 AND NAM = 2006
)

-- CAU 8
SELECT HO, TEN
FROM HOCVIEN
WHERE MAHV IN (
	SELECT TRGLOP
	FROM LOP
	WHERE MALOP IN (
		SELECT MALOP
		FROM GIANGDAY
		WHERE MAGV IN (
			SELECT MAGV
			FROM GIAOVIEN
			WHERE HOTEN = 'Nguyen To Lan'
		) AND MAMH = 'CSDL'
	)
)


-- CAU 9
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN (
	SELECT MAMH_TRUOC
	FROM DIEUKIEN
	WHERE MAMH = 'CSDL'
)

-- CAU 10
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN (
	SELECT MAMH
	FROM DIEUKIEN
	WHERE MAMH_TRUOC = 'CSDL'
)

-- BAI TAP 5
-- PHAN III CAU 11 DEN 18
-- CAU 11
SELECT HOTEN
FROM GIANGDAY JOIN GIAOVIEN
ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE MALOP = 'K11' AND MAMH = 'CTRR' AND HOCKY = 1 AND NAM = 2006
INTERSECT
SELECT HOTEN
FROM GIANGDAY JOIN GIAOVIEN
ON GIANGDAY.MAGV = GIAOVIEN.MAGV
WHERE MALOP = 'K12' AND MAMH = 'CTRR' AND HOCKY = 1 AND NAM = 2006

-- CAU 12
SELECT HOCVIEN.MAHV, HO, TEN
FROM HOCVIEN 
WHERE MAHV IN (
	SELECT MAHV
	FROM KETQUATHI A
	WHERE NOT EXISTS (
		SELECT 1 
		FROM KETQUATHI B
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
	) AND MAMH = 'CSDL'  AND LANTHI = 1 AND KQUA = 'Khong dat'
)

-- CAU 13
SELECT MAGV, HOTEN 
FROM GIAOVIEN 
WHERE MAGV NOT IN (
	SELECT DISTINCT MAGV 
	FROM GIANGDAY
)

-- CAU 14
SELECT MAGV, HOTEN FROM GIAOVIEN 
WHERE MAGV NOT IN (
	SELECT GD.MAGV
	FROM GIANGDAY GD INNER JOIN GIAOVIEN GV 
	ON GD.MAGV = GV.MAGV INNER JOIN MONHOC MH
	ON GD.MAMH = MH.MAMH
	WHERE GV.MAKHOA = MH.MAKHOA
)

-- CAU 15
SELECT HO, TEN 
FROM HOCVIEN
WHERE MAHV IN (
	SELECT MAHV 
	FROM KETQUATHI A
	WHERE LEFT(MAHV, 3) = 'K11' AND (
		NOT EXISTS (
			SELECT 1 
			FROM KETQUATHI B 
			WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
		)  AND LANTHI = 3 AND KQUA = 'Khong Dat'
	) OR MAMH = 'CTRR' AND LANTHI = 2 AND DIEM = 5
)

-- CAU 16
SELECT HOTEN 
FROM GIAOVIEN 
WHERE MAGV IN (
	SELECT MAGV 
	FROM GIANGDAY 
	WHERE MAMH = 'CTRR'
	GROUP BY MAGV, HOCKY, NAM 
	HAVING COUNT(MALOP) >= 2
)

-- CAU 17
SELECT HV.MAHV, HO, TEN, DIEM 
FROM HOCVIEN HV INNER JOIN (
	SELECT MAHV, DIEM 
	FROM KETQUATHI A
	WHERE NOT EXISTS (
		SELECT 1 
		FROM KETQUATHI B 
		WHERE A.MAHV = B.MAHV AND A.MAMH = B.MAMH AND A.LANTHI < B.LANTHI
	) AND MAMH = 'CSDL'
) DIEM_CSDL
ON HV.MAHV = DIEM_CSDL.MAHV

-- CAU 18
SELECT HV.MAHV, HO, TEN, DIEM 
FROM HOCVIEN HV INNER JOIN (
	SELECT MAHV, MAX(DIEM) AS DIEM FROM KETQUATHI 
	WHERE MAMH IN (
		SELECT MAMH FROM MONHOC 
		WHERE TENMH = 'Co So Du Lieu'
	) 
	GROUP BY MAHV, MAMH
) DIEM_CSDL_MAX
ON HV.MAHV = DIEM_CSDL_MAX.MAHV