CREATE DATABASE BAITHI

USE BAITHI

CREATE TABLE NHACUNGCAP (
	MANCC CHAR(5) PRIMARY KEY, 
	TENNCC VARCHAR(40), 
	QUOCGIA VARCHAR(40), 
	LOAINCC VARCHAR(20),
);

CREATE TABLE DUOCPHAM (
	MADP CHAR(4) PRIMARY KEY,
	TENDP VARCHAR(40),
	LOAIDP VARCHAR(10),
	GIA MONEY,
);

CREATE TABLE PHIEUNHAP (
	SOPN CHAR(5) PRIMARY KEY,
	NGNHAP SMALLDATETIME, 
	MANCC CHAR(5),
	LOAINHAP VARCHAR(20),
);

CREATE TABLE CTPN (
	SOPN CHAR(5),
	MADP CHAR(4),
	SOLUONG INT,
	CONSTRAINT PK_CTPN PRIMARY KEY(SOPN, MADP),
);

ALTER TABLE PHIEUNHAP ADD
CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)

ALTER TABLE CTPN ADD
CONSTRAINT FK_CTPN_NCC FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
CONSTRAINT FK_CTPN_DP FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP)

INSERT INTO NHACUNGCAP (MANCC, TENNCC, QUOCGIA, LOAINCC)
VALUES
('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen'),
('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai'),
('NCC03', 'Sapharco', 'Singapore', 'Vang lai');

INSERT INTO DUOCPHAM (MADP, TENDP, LOAIDP, GIA)
VALUES
('DP01', 'Thuoc ho PH', 'Siro', 120000),
('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', 200000),
('DP03', 'Cotrim', 'Vien sui', 80000);

INSERT INTO PHIEUNHAP (SOPN, NGNHAP, MANCC, LOAINHAP)
VALUES
('00001', '2017-11-22', 'NCC01', 'Noi dia'),
('00002', '2017-12-04', 'NCC02', 'Nhap khau'),
('00003', '2017-12-10', 'NCC03', 'Nhap khau');

INSERT INTO CTPN (SOPN, MADP, SOLUONG)
VALUES
('00001', 'DP01', 100),
('00002', 'DP02', 200),
('00003', 'DP03', 543);

ALTER TABLE DUOCPHAM ADD CONSTRAINT CHK_DP
CHECK (LOAIDP != 'Siro' OR GIA >= 100000)

CREATE TRIGGER TRG_QUG_LN ON NHACUNGCAP
FOR INSERT
AS
BEGIN
	DECLARE @QuocGia VARCHAR(40), @MaNCC CHAR(5), @LoaiNhap VARCHAR(20)
	SELECT @QuocGia = QUOCGIA, @MaNCC = MANCC
	FROM INSERTED 
	
	IF (@QuocGia = 'Viet nam')
	BEGIN
		SET @LoaiNhap = 'Noi dia'
	END
	ELSE
	BEGIN 
		SET @LoaiNhap = 'Nhap khau'
	END

	UPDATE PHIEUNHAP SET LOAINHAP = @LoaiNhap WHERE MANCC = @MaNCC
END

SELECT *
FROM PHIEUNHAP
WHERE YEAR(NGNHAP) = 2017 AND MONTH(NGNHAP) = 12
ORDER BY NGNHAP


