CREATE DATABASE TH_CSDL_DE04
GO

USE DATABASE TH_CSDL_DE04
GO

CREATE TABLE KHACHHANG (
	MaKH char(5), 
	HoTen varchar(30),
	DiaChi varchar(30),
	SoDT varchar(15),
	LoaiKH varchar(10),
	CONSTRAINT pk_kh PRIMARY KEY (MaKH)
); 

CREATE TABLE BANG_DIA (
	MaBD char(5),
	TenBD varchar(25),
	TheLoai varchar(25),
	CONSTRAINT pk_bd PRIMARY KEY (MaBD)
);

CREATE TABLE PHIEUTHUE (
	MaPT char(5),
	MaKH char(5),
	NgayThue smalldatetime,
	NgayTra smalldatetime,
	SoLuongThue int,
	CONSTRAINT pk_pt PRIMARY KEY (MaPT),
	CONSTRAINT fk_pt_kh FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE CHITIET_PM (
	MaPT char(5),
	MaBD char(5),
	CONSTRAINT pk_ctpm PRIMARY KEY (MaPT, MaBD),
	CONSTRAINT fk_ctpm_pt FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT),
	CONSTRAINT fk_ctpm_bd FOREIGN KEY (MaBD) REFERENCES BANG_DIA(MaBD)
);

ALTER TABLE BANG_DIA ADD CONSTRAINT chk_thl 
CHECK (TheLoai IN ('ca nhac', 'phim hanh dong', 'phim tinh cam', 'phim hoat hinh'))
GO

CREATE TRIGGER trg_vip_slg ON PHIEUTHUE
FOR INSERT
AS
BEGIN
	DECLARE @MaKH char(5), @LoaiKH varchar(10), @SoLgThue int
	SELECT @MaKH = MaKH, @SoLgThue = SoLuongThue
	FROM INSERTED 

	SELECT @LoaiKH = LoaiKH
	FROM KHACHHANG
	WHERE MaKH = @MaKH

	IF (@SoLgThue > 5 AND @LoaiKH <> 'VIP')
	BEGIN 
		PRINT N'Chỉ có khách hàng thuộc loại VIP mới được thuê với số lượng băng đĩa trên 5'
		ROLLBACK TRANSACTION
	END
END

SELECT PHIEUTHUE.MaKH, HoTen
FROM KHACHHANG 
JOIN PHIEUTHUE ON PHIEUTHUE.MaKH = KHACHHANG.MaKH
JOIN CHITIET_PM ON CHITIET_PM.MaPT = PHIEUTHUE.MaPT
JOIN BANG_DIA ON CHITIET_PM.MaBD = BANG_DIA.MaBD
WHERE TheLoai = 'Tinh cam' AND SoLuongThue > 3

SELECT TOP 3 PHIEUTHUE.MaKH, HoTen
FROM KHACHHANG JOIN PHIEUTHUE
ON KHACHHANG.MaKH = PHIEUTHUE.MaKH
WHERE LoaiKH = 'VIP'
ORDER BY SoLuongThue DESC

WITH BANGDIA_SOLUONGTHUE AS (
	SELECT MaKH, SUM(SoLuongThue) AS TongSoLuong, TheLoai
	FROM PHIEUTHUE 
	JOIN CHITIET_PM ON PHIEUTHUE.MaPT = CHITIET_PM.MaPT
	JOIN BANG_DIA ON CHITIET_PM.MaBD = BANG_DIA.MaBD
	GROUP BY TheLoai, MaKH
), THELOAI_MAX AS (
	SELECT MaKH, 
		ROW_NUMBER() OVER (PARTITION BY TheLoai ORDER BY TongSoLuong DESC) AS Rank
	FROM BANGDIA_SOLUONGTHUE 
)
SELECT HoTen AS KhachHangThueNhieuNhat
FROM THELOAI_MAX JOIN KHACHHANG
ON THELOAI_MAX.MaKH = KHACHHANG.MaKH
WHERE Rank = 1